# Generated by Django 5.2.17 on 2026-09-01 14:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('interest', 'Quero aplicar'), ('applied', 'Aplicada'), ('screening', 'Em triagem'), ('challenge', 'Teste / desafio'), ('interview', 'Entrevista'), ('offer', 'Proposta'), ('rejected', 'Rejeitada'), ('withdrawn', 'Desisti')], db_index=True, default='interest', max_length=20, verbose_name='Status')),
                ('priority', models.PositiveSmallIntegerField(default=3, help_text='1 = maior prioridade, 5 = menor', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Prioridade')),
                ('applied_on', models.DateField(blank=True, null=True, verbose_name='Aplicada em')),
                ('next_step', models.CharField(blank=True, max_length=300, verbose_name='Próximo passo')),
                ('next_step_on', models.DateField(blank=True, db_index=True, null=True, verbose_name='Data do próximo passo')),
                ('contact', models.CharField(blank=True, help_text='Recrutador, indicação, quem te respondeu', max_length=200, verbose_name='Contato')),
                ('has_referral', models.BooleanField(default=False, verbose_name='Tem indicação')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='jobs.job')),
            ],
            options={
                'verbose_name': 'candidatura',
                'verbose_name_plural': 'candidaturas',
                'db_table': 'pipeline_application',
                'ordering': ['priority', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('detail', models.TextField(blank=True, verbose_name='Detalhe')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='pipeline.application')),
            ],
            options={
                'verbose_name': 'interação',
                'verbose_name_plural': 'interações',
                'db_table': 'pipeline_interaction',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status', 'priority'], name='application_status_prio_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['application', '-date'], name='interaction_app_date_idx'),
        ),
    ]
