# Generated by Django 5.2.17 on 2026-09-02 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Chave')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'cargo',
                'verbose_name_plural': 'cargos',
                'db_table': 'accounts_cargo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Permissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Chave')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('descricao', models.CharField(blank=True, max_length=300, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'permissão',
                'verbose_name_plural': 'permissões',
                'db_table': 'accounts_permissao',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, max_length=120, verbose_name='Nome')),
                ('dossie', models.TextField(blank=True, verbose_name='Dossiê')),
                ('termos', models.JSONField(blank=True, default=dict, verbose_name='Termos de scoring')),
                ('pitch_max_chars', models.PositiveIntegerField(default=1200, verbose_name='Tamanho da apresentação')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='perfis', to='accounts.cargo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'perfil',
                'verbose_name_plural': 'perfis',
                'db_table': 'accounts_perfil',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='permissoes',
            field=models.ManyToManyField(blank=True, related_name='cargos', to='accounts.permissao'),
        ),
    ]
