# Generated by Django 5.2.17 on 2026-09-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_cargo_dono'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='codigos_de_reserva',
            field=models.JSONField(blank=True, default=list, verbose_name='Códigos de reserva'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='totp_ativo',
            field=models.BooleanField(default=False, verbose_name='2FA ativo'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=64, verbose_name='Segredo TOTP'),
        ),
    ]
