# Generated by Django 5.2.17 on 2026-09-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_perfil_codigos_de_reserva_perfil_totp_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='totp_ultimo_passo',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Último passo TOTP'),
        ),
    ]
