# Generated by Django 5.2.17 on 2026-09-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='Título')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Local')),
                ('work_mode', models.CharField(choices=[('remote', 'Remoto'), ('hybrid', 'Híbrido'), ('onsite', 'Presencial'), ('unknown', 'Não informado')], default='unknown', max_length=20, verbose_name='Modalidade')),
                ('seniority', models.CharField(choices=[('internship', 'Estágio'), ('junior', 'Júnior'), ('mid', 'Pleno'), ('senior', 'Sênior'), ('unknown', 'Não informado')], default='unknown', max_length=20, verbose_name='Senioridade')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('url', models.URLField(max_length=1000)),
                ('source', models.CharField(choices=[('github', 'GitHub Issues'), ('gupy', 'Gupy'), ('manual', 'Cadastro manual')], db_index=True, max_length=20, verbose_name='Fonte')),
                ('source_id', models.CharField(blank=True, max_length=200, verbose_name='ID na fonte')),
                ('key', models.CharField(editable=False, max_length=64, unique=True)),
                ('score', models.IntegerField(db_index=True, default=0)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Publicada em')),
                ('discarded', models.BooleanField(db_index=True, default=False, verbose_name='Descartada')),
            ],
            options={
                'verbose_name': 'vaga',
                'verbose_name_plural': 'vagas',
                'db_table': 'jobs_job',
                'ordering': ['-score', '-created_at'],
                'indexes': [models.Index(fields=['discarded', '-score'], name='job_discarded_score_idx'), models.Index(fields=['source', '-created_at'], name='job_source_created_idx')],
            },
        ),
    ]
