# Generated by Django 5.2.17 on 2026-09-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Publicada em'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['discarded', '-published_at'], name='job_discarded_pub_idx'),
        ),
    ]
