# Generated by Django 5.2.17 on 2026-09-02 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_published_at_job_job_discarded_pub_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField(verbose_name='Texto')),
                ('modelo', models.CharField(max_length=80, verbose_name='Modelo')),
                ('instrucao', models.CharField(blank=True, max_length=300, verbose_name='Ajuste pedido')),
                ('max_chars', models.PositiveIntegerField(verbose_name='Tamanho alvo')),
                ('tokens_entrada', models.PositiveIntegerField(default=0)),
                ('tokens_saida', models.PositiveIntegerField(default=0)),
                ('tokens_pensamento', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to='jobs.job')),
            ],
            options={
                'verbose_name': 'apresentação',
                'verbose_name_plural': 'apresentações',
                'db_table': 'jobs_pitch',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['job', '-created_at'], name='pitch_job_created_idx')],
            },
        ),
    ]
