# Generated by Django 5.2.17 on 2026-09-04 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_pitch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pitch',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitches', to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AddIndex(
            model_name='pitch',
            index=models.Index(fields=['autor', '-created_at'], name='pitch_autor_created_idx'),
        ),
    ]
