# Generated by Django 5.2.17 on 2026-09-01 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('github', 'GitHub Issues'), ('gupy', 'Gupy'), ('manual', 'Cadastro manual')], max_length=20, verbose_name='Fonte')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Fim')),
                ('found_count', models.IntegerField(default=0, verbose_name='Encontradas')),
                ('new_count', models.IntegerField(default=0, verbose_name='Novas')),
                ('error', models.TextField(blank=True, verbose_name='Erro')),
            ],
            options={
                'verbose_name': 'coleta',
                'verbose_name_plural': 'coletas',
                'db_table': 'collectors_run',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', '-started_at'], name='run_source_started_idx')],
            },
        ),
    ]
